spring:
  application:
    name: Loan Request Service
  data:
    jpa:
      repositories:
        bootstrap-mode: default
  datasource:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true
eureka:
  client:
    fetch-registry: false
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8095