logging:
  level:
    org:
      hibernate: DEBUG
      springframework:
        web: DEBUG
server:
  port: 8090
spring:
  datasource:
    password: pass
    url: jdbc:mysql://localhost:3306/loan_schema?autoReconnect=true&useSSL=false
    username: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
eureka:
  client:
    fetch-registry: false
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka